version: "3.3"
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
  ratecurrency-webapp:
    image: ratecurrency/demo:latest
    depends_on:
      - postgres
    ports:
      - 9000:9000